SELECT 'CREATE DATABASE money_tracker'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'money_tracker')\gexec

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.account (
    account_id integer NOT NULL,
    name text NOT NULL,
    type text
);

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.budget (
    budget_id integer NOT NULL,
    name text NOT NULL,
    category_ids integer[] NOT NULL,
    amount numeric DEFAULT 0.00 NOT NULL
);

ALTER TABLE public.budget ALTER COLUMN budget_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.category (
    category_id integer NOT NULL,
    name text NOT NULL,
    parent_id integer
);

ALTER TABLE public.category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.label (
    label_id integer NOT NULL,
    name text
);

ALTER TABLE public.label ALTER COLUMN label_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.label_label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.rule (
    rule_id integer NOT NULL,
    description text NOT NULL,
    category_id integer NOT NULL,
    order_id integer
);

ALTER TABLE public.rule ALTER COLUMN rule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rule_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transaction (
    transaction_id bigint NOT NULL,
    date date NOT NULL,
    description text NOT NULL,
    account_id integer DEFAULT '-1'::integer,
    category_id integer DEFAULT '-1'::integer,
    is_hidden boolean DEFAULT false NOT NULL,
    is_pending boolean DEFAULT true NOT NULL,
    is_duplicated boolean DEFAULT false NOT NULL,
    amount numeric DEFAULT 0.00 NOT NULL,
    note text,
    label_ids integer[]
);

ALTER TABLE public.transaction ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);

ALTER TABLE ONLY public.budget
    ADD CONSTRAINT budget_pkey PRIMARY KEY (budget_id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);

ALTER TABLE ONLY public.label
    ADD CONSTRAINT label_pkey PRIMARY KEY (label_id);

ALTER TABLE ONLY public.rule
    ADD CONSTRAINT rule_pkey PRIMARY KEY (rule_id);

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id);

CREATE INDEX fki_fk_account_id ON public.transaction USING btree (account_id);

CREATE INDEX fki_fk_category_id ON public.transaction USING btree (category_id);

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk_account_id FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES public.category(category_id) ON UPDATE RESTRICT ON DELETE RESTRICT;

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


COPY public.category (category_id, name, parent_id) FROM stdin;
1	Auto	\N
9	Utilities	\N
15	Cash	\N
16	Charity	\N
17	Entertainment	\N
18	Bank Fees	\N
19	Food	\N
24	Gifts	\N
25	Health	\N
26	Home	\N
30	Income	\N
35	Shopping	\N
39	Taxes	\N
44	Transfers	\N
45	Credit Card Payment	44
46	Travel	\N
2	Auto - Gas	1
3	Auto - Insurance	1
4	Auto - Parking	1
5	Auto - Registration	1
6	Auto - Service	1
7	Auto - Tickets	1
8	Auto - Transportation	1
10	Utilities - Electricity	9
11	Utilities - Gas	9
12	Utilities - Internet	9
13	Utilities - Phone	9
14	Utilities - Water	9
20	Food - Groceries	19
21	Food - Meng Eats	19
22	Food - Restaurants	19
23	Food - Xiao Eats	19
27	Home - Investment	26
28	Home - Rent	26
29	Home - Maintenance	26
31	Income - Bonus	30
32	Income - Interest	30
33	Income - Others	30
34	Income - Paycheck	30
36	Shopping - Household	35
37	Shopping - Meng	35
38	Shopping - Xiao	35
40	Taxes - Federal	39
41	Taxes - Others	39
42	Taxes - State	39
43	Taxes - Property	39
47	Travel - Air	46
48	Travel - Food	46
49	Travel - Lodging	46
50	Travel - Others	46
51	Travel - Transportation	46
\.

SELECT pg_catalog.setval('public.category_category_id_seq', 52, true);

